name: 'Current NPM Package Version'
description: 'Get the current version in package.json'
branding:
  icon: hash
  color: blue
outputs:
  version:
    description: 'Current package version from package.json'
runs:
  using: 'composite'
  steps:
    - run: pwd
      shell: bash
    - run: ls -al
      shell: bash
    - run: 'node index.js'
      shell: bash